openapi: 3.0.0
info:
  title: Grade Domain API
  description: An API used for CRUD operations on grades for players
  version: 1.0.0
paths:
  /grades/{gradeId}:
    patch:
      summary: Updates a grade
      parameters:
        - name: gradeId
          in: path
          required: true
          description: Id Number of the grade
          schema:
            type : integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                grade:
                  type: string
      responses:
        '200':
          description: A message that confirms the successful update of the grade
        '400':
          description: A message communicating that the grade could not be updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reasonForFailure:
                    type: string
                    example: Grade was not in range 'A-F'
    delete:
      summary: Deletes a grade
      parameters:
        - name: gradeId
          in: path
          required: true
          description: Id Number of the grade
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A message that confirms the deletion of the grade.
        '400':
          description: A message communicating that the grade could not be deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reasonForFailure:
                    type: string
                    example: Invalid Grade Id